input {
  tcp {
    port => 5000
    codec => json_lines
  }
  beats {
    port => 5044
  }
}

filter {
  mutate {
    add_field => { "message" => "%{[_docker][log]}" }
  }
}

filter {
  mutate {
    remove_field => ["log", "_docker"]
  }
}

output {
  elasticsearch {
    hosts => ["http://es-master:9200"]
    index => "logstash-%{+YYYY.MM.dd}"
  }
}

